{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"gpuType":"T4","mount_file_id":"1pYKhnTceFxXqletxY-Z723lgHhI2iEuP","authorship_tag":"ABX9TyOBh5Bu5go6u/KTXzI3IpIT"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"},"accelerator":"GPU"},"cells":[{"cell_type":"code","source":["!nvidia-smi"],"metadata":{"id":"8n7AKc8Wo44b"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["from google.colab import drive\n","drive.mount('/content/drive')"],"metadata":{"id":"gwfghDBH_Z_8"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["!git clone https://github.com/zhengyao603/Cantolater"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"e-Ys4CJI3qgl","executionInfo":{"status":"ok","timestamp":1711896749310,"user_tz":-480,"elapsed":1534,"user":{"displayName":"gracias","userId":"12064270699339955558"}},"outputId":"4c0c6749-945e-4ec6-a896-f81ec62374a5"},"execution_count":3,"outputs":[{"output_type":"stream","name":"stdout","text":["Cloning into 'Cantolater'...\n","remote: Enumerating objects: 246, done.\u001b[K\n","remote: Counting objects: 100% (246/246), done.\u001b[K\n","remote: Compressing objects: 100% (199/199), done.\u001b[K\n","remote: Total 246 (delta 26), reused 234 (delta 26), pack-reused 0\u001b[K\n","Receiving objects: 100% (246/246), 2.56 MiB | 27.55 MiB/s, done.\n","Resolving deltas: 100% (26/26), done.\n"]}]},{"cell_type":"code","source":["!pip install -r /content/Cantolater/requirements.txt"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"MGAzJYE74CQ4","executionInfo":{"status":"ok","timestamp":1711896976408,"user_tz":-480,"elapsed":7528,"user":{"displayName":"gracias","userId":"12064270699339955558"}},"outputId":"d730a137-c83f-47fb-e91b-13938b090b47"},"execution_count":1,"outputs":[{"output_type":"stream","name":"stdout","text":["Requirement already satisfied: ConfigArgParse in /usr/local/lib/python3.10/dist-packages (from -r /content/Cantolater/requirements.txt (line 1)) (1.7)\n","Requirement already satisfied: configparser in /usr/local/lib/python3.10/dist-packages (from -r /content/Cantolater/requirements.txt (line 2)) (6.0.1)\n","Requirement already satisfied: datasets in /usr/local/lib/python3.10/dist-packages (from -r /content/Cantolater/requirements.txt (line 3)) (2.18.0)\n","Requirement already satisfied: numba in /usr/local/lib/python3.10/dist-packages (from -r /content/Cantolater/requirements.txt (line 4)) (0.58.1)\n","Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from -r /content/Cantolater/requirements.txt (line 5)) (1.25.2)\n","Requirement already satisfied: sacrebleu in /usr/local/lib/python3.10/dist-packages (from -r /content/Cantolater/requirements.txt (line 6)) (2.4.1)\n","Requirement already satisfied: sacremoses in /usr/local/lib/python3.10/dist-packages (from -r /content/Cantolater/requirements.txt (line 7)) (0.1.1)\n","Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from -r /content/Cantolater/requirements.txt (line 8)) (1.2.2)\n","Requirement already satisfied: tensorboard in /usr/local/lib/python3.10/dist-packages (from -r /content/Cantolater/requirements.txt (line 9)) (2.15.2)\n","Requirement already satisfied: tensorboardX in /usr/local/lib/python3.10/dist-packages (from -r /content/Cantolater/requirements.txt (line 10)) (2.6.2.2)\n","Requirement already satisfied: tokenizers in /usr/local/lib/python3.10/dist-packages (from -r /content/Cantolater/requirements.txt (line 11)) (0.15.2)\n","Requirement already satisfied: torch in /usr/local/lib/python3.10/dist-packages (from -r /content/Cantolater/requirements.txt (line 12)) (2.2.1+cu121)\n","Requirement already satisfied: torch-tb-profiler in /usr/local/lib/python3.10/dist-packages (from -r /content/Cantolater/requirements.txt (line 13)) (0.4.3)\n","Requirement already satisfied: torchtext in /usr/local/lib/python3.10/dist-packages (from -r /content/Cantolater/requirements.txt (line 14)) (0.17.1)\n","Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from -r /content/Cantolater/requirements.txt (line 15)) (4.66.2)\n","Requirement already satisfied: transformers in /usr/local/lib/python3.10/dist-packages (from -r /content/Cantolater/requirements.txt (line 16)) (4.38.2)\n","Requirement already satisfied: protobuf==3.20.0 in /usr/local/lib/python3.10/dist-packages (from -r /content/Cantolater/requirements.txt (line 17)) (3.20.0)\n","Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from datasets->-r /content/Cantolater/requirements.txt (line 3)) (3.13.3)\n","Requirement already satisfied: pyarrow>=12.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets->-r /content/Cantolater/requirements.txt (line 3)) (14.0.2)\n","Requirement already satisfied: pyarrow-hotfix in /usr/local/lib/python3.10/dist-packages (from datasets->-r /content/Cantolater/requirements.txt (line 3)) (0.6)\n","Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from datasets->-r /content/Cantolater/requirements.txt (line 3)) (0.3.8)\n","Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from datasets->-r /content/Cantolater/requirements.txt (line 3)) (1.5.3)\n","Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.10/dist-packages (from datasets->-r /content/Cantolater/requirements.txt (line 3)) (2.31.0)\n","Requirement already satisfied: xxhash in /usr/local/lib/python3.10/dist-packages (from datasets->-r /content/Cantolater/requirements.txt (line 3)) (3.4.1)\n","Requirement already satisfied: multiprocess in /usr/local/lib/python3.10/dist-packages (from datasets->-r /content/Cantolater/requirements.txt (line 3)) (0.70.16)\n","Requirement already satisfied: fsspec[http]<=2024.2.0,>=2023.1.0 in /usr/local/lib/python3.10/dist-packages (from datasets->-r /content/Cantolater/requirements.txt (line 3)) (2023.6.0)\n","Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets->-r /content/Cantolater/requirements.txt (line 3)) (3.9.3)\n","Requirement already satisfied: huggingface-hub>=0.19.4 in /usr/local/lib/python3.10/dist-packages (from datasets->-r /content/Cantolater/requirements.txt (line 3)) (0.20.3)\n","Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from datasets->-r /content/Cantolater/requirements.txt (line 3)) (24.0)\n","Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from datasets->-r /content/Cantolater/requirements.txt (line 3)) (6.0.1)\n","Requirement already satisfied: llvmlite<0.42,>=0.41.0dev0 in /usr/local/lib/python3.10/dist-packages (from numba->-r /content/Cantolater/requirements.txt (line 4)) (0.41.1)\n","Requirement already satisfied: portalocker in /usr/local/lib/python3.10/dist-packages (from sacrebleu->-r /content/Cantolater/requirements.txt (line 6)) (2.8.2)\n","Requirement already satisfied: regex in /usr/local/lib/python3.10/dist-packages (from sacrebleu->-r /content/Cantolater/requirements.txt (line 6)) (2023.12.25)\n","Requirement already satisfied: tabulate>=0.8.9 in /usr/local/lib/python3.10/dist-packages (from sacrebleu->-r /content/Cantolater/requirements.txt (line 6)) (0.9.0)\n","Requirement already satisfied: colorama in /usr/local/lib/python3.10/dist-packages (from sacrebleu->-r /content/Cantolater/requirements.txt (line 6)) (0.4.6)\n","Requirement already satisfied: lxml in /usr/local/lib/python3.10/dist-packages (from sacrebleu->-r /content/Cantolater/requirements.txt (line 6)) (4.9.4)\n","Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from sacremoses->-r /content/Cantolater/requirements.txt (line 7)) (8.1.7)\n","Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from sacremoses->-r /content/Cantolater/requirements.txt (line 7)) (1.3.2)\n","Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->-r /content/Cantolater/requirements.txt (line 8)) (1.11.4)\n","Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->-r /content/Cantolater/requirements.txt (line 8)) (3.4.0)\n","Requirement already satisfied: absl-py>=0.4 in /usr/local/lib/python3.10/dist-packages (from tensorboard->-r /content/Cantolater/requirements.txt (line 9)) (1.4.0)\n","Requirement already satisfied: grpcio>=1.48.2 in /usr/local/lib/python3.10/dist-packages (from tensorboard->-r /content/Cantolater/requirements.txt (line 9)) (1.62.1)\n","Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.10/dist-packages (from tensorboard->-r /content/Cantolater/requirements.txt (line 9)) (2.27.0)\n","Requirement already satisfied: google-auth-oauthlib<2,>=0.5 in /usr/local/lib/python3.10/dist-packages (from tensorboard->-r /content/Cantolater/requirements.txt (line 9)) (1.2.0)\n","Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.10/dist-packages (from tensorboard->-r /content/Cantolater/requirements.txt (line 9)) (3.6)\n","Requirement already satisfied: setuptools>=41.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard->-r /content/Cantolater/requirements.txt (line 9)) (67.7.2)\n","Requirement already satisfied: six>1.9 in /usr/local/lib/python3.10/dist-packages (from tensorboard->-r /content/Cantolater/requirements.txt (line 9)) (1.16.0)\n","Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard->-r /content/Cantolater/requirements.txt (line 9)) (0.7.2)\n","Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from tensorboard->-r /content/Cantolater/requirements.txt (line 9)) (3.0.1)\n","Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from torch->-r /content/Cantolater/requirements.txt (line 12)) (4.10.0)\n","Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch->-r /content/Cantolater/requirements.txt (line 12)) (1.12)\n","Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch->-r /content/Cantolater/requirements.txt (line 12)) (3.2.1)\n","Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch->-r /content/Cantolater/requirements.txt (line 12)) (3.1.3)\n","Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /usr/local/lib/python3.10/dist-packages (from torch->-r /content/Cantolater/requirements.txt (line 12)) (12.1.105)\n","Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /usr/local/lib/python3.10/dist-packages (from torch->-r /content/Cantolater/requirements.txt (line 12)) (12.1.105)\n","Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /usr/local/lib/python3.10/dist-packages (from torch->-r /content/Cantolater/requirements.txt (line 12)) (12.1.105)\n","Requirement already satisfied: nvidia-cudnn-cu12==8.9.2.26 in /usr/local/lib/python3.10/dist-packages (from torch->-r /content/Cantolater/requirements.txt (line 12)) (8.9.2.26)\n","Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /usr/local/lib/python3.10/dist-packages (from torch->-r /content/Cantolater/requirements.txt (line 12)) (12.1.3.1)\n","Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /usr/local/lib/python3.10/dist-packages (from torch->-r /content/Cantolater/requirements.txt (line 12)) (11.0.2.54)\n","Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /usr/local/lib/python3.10/dist-packages (from torch->-r /content/Cantolater/requirements.txt (line 12)) (10.3.2.106)\n","Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /usr/local/lib/python3.10/dist-packages (from torch->-r /content/Cantolater/requirements.txt (line 12)) (11.4.5.107)\n","Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /usr/local/lib/python3.10/dist-packages (from torch->-r /content/Cantolater/requirements.txt (line 12)) (12.1.0.106)\n","Requirement already satisfied: nvidia-nccl-cu12==2.19.3 in /usr/local/lib/python3.10/dist-packages (from torch->-r /content/Cantolater/requirements.txt (line 12)) (2.19.3)\n","Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /usr/local/lib/python3.10/dist-packages (from torch->-r /content/Cantolater/requirements.txt (line 12)) (12.1.105)\n","Requirement already satisfied: triton==2.2.0 in /usr/local/lib/python3.10/dist-packages (from torch->-r /content/Cantolater/requirements.txt (line 12)) (2.2.0)\n","Requirement already satisfied: nvidia-nvjitlink-cu12 in /usr/local/lib/python3.10/dist-packages (from nvidia-cusolver-cu12==11.4.5.107->torch->-r /content/Cantolater/requirements.txt (line 12)) (12.4.99)\n","Requirement already satisfied: torchdata==0.7.1 in /usr/local/lib/python3.10/dist-packages (from torchtext->-r /content/Cantolater/requirements.txt (line 14)) (0.7.1)\n","Requirement already satisfied: urllib3>=1.25 in /usr/local/lib/python3.10/dist-packages (from torchdata==0.7.1->torchtext->-r /content/Cantolater/requirements.txt (line 14)) (2.0.7)\n","Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers->-r /content/Cantolater/requirements.txt (line 16)) (0.4.2)\n","Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->-r /content/Cantolater/requirements.txt (line 3)) (1.3.1)\n","Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->-r /content/Cantolater/requirements.txt (line 3)) (23.2.0)\n","Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->-r /content/Cantolater/requirements.txt (line 3)) (1.4.1)\n","Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->-r /content/Cantolater/requirements.txt (line 3)) (6.0.5)\n","Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->-r /content/Cantolater/requirements.txt (line 3)) (1.9.4)\n","Requirement already satisfied: async-timeout<5.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->-r /content/Cantolater/requirements.txt (line 3)) (4.0.3)\n","Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard->-r /content/Cantolater/requirements.txt (line 9)) (5.3.3)\n","Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard->-r /content/Cantolater/requirements.txt (line 9)) (0.4.0)\n","Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard->-r /content/Cantolater/requirements.txt (line 9)) (4.9)\n","Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from google-auth-oauthlib<2,>=0.5->tensorboard->-r /content/Cantolater/requirements.txt (line 9)) (1.4.1)\n","Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets->-r /content/Cantolater/requirements.txt (line 3)) (2.8.2)\n","Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets->-r /content/Cantolater/requirements.txt (line 3)) (2023.4)\n","Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->datasets->-r /content/Cantolater/requirements.txt (line 3)) (3.3.2)\n","Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->datasets->-r /content/Cantolater/requirements.txt (line 3)) (3.6)\n","Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->datasets->-r /content/Cantolater/requirements.txt (line 3)) (2024.2.2)\n","Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.10/dist-packages (from werkzeug>=1.0.1->tensorboard->-r /content/Cantolater/requirements.txt (line 9)) (2.1.5)\n","Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch->-r /content/Cantolater/requirements.txt (line 12)) (1.3.0)\n","Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in /usr/local/lib/python3.10/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard->-r /content/Cantolater/requirements.txt (line 9)) (0.6.0)\n","Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<2,>=0.5->tensorboard->-r /content/Cantolater/requirements.txt (line 9)) (3.2.2)\n"]}]},{"cell_type":"code","source":["!python /content/Cantolater/main.py"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"P4lPhO4F33ph","executionInfo":{"status":"ok","timestamp":1711898246083,"user_tz":-480,"elapsed":15356,"user":{"displayName":"gracias","userId":"12064270699339955558"}},"outputId":"e47d444e-a2c3-4fb4-a38c-856cca5d4ea9"},"execution_count":10,"outputs":[{"output_type":"stream","name":"stdout","text":["2024-03-31 15:17:15.854279: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered\n","2024-03-31 15:17:15.854334: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered\n","2024-03-31 15:17:15.856207: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n","2024-03-31 15:17:17.158609: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT\n","{'dataset_name': 'origin', 'src_pretrain_dataset_name': 'bert-base-chinese', 'tgt_pretrain_dataset_name': 'gpt2', 'train_data_path': '/content/Cantolater/dataset/train.txt', 'eval_data_path': None, 'run_path': '/content/Cantolater/runs/', 'output_dir': '/content/Cantolater/checkpoints/', 'optimizer': 'adam', 'lr': 1e-07, 'finetune_lr': 1e-05, 'ngpu': 1, 'seed': 17, 'max_src_len': 128, 'max_tgt_len': 128, 'save_step': 100, 'num_training_steps': 100, 'num_warmup_steps': 100, 'nepoch': 1, 'num_workers': 16, 'train_batch_size': 32, 'eval_batch_size': 32, 'drop_last': False, 'ispredict': False, 'save_optimizer': False, 'train_dataset_ratio': 0.999, 'model_path': None, 'local_rank': -1}\n","You are using a model of type bert to instantiate a model of type bert-generation. This is not supported for all configurations of models and can yield errors.\n","Some weights of GPT2LMHeadModel were not initialized from the model checkpoint at gpt2 and are newly initialized: ['h.0.crossattention.c_attn.bias', 'h.0.crossattention.c_attn.weight', 'h.0.crossattention.c_proj.bias', 'h.0.crossattention.c_proj.weight', 'h.0.crossattention.q_attn.bias', 'h.0.crossattention.q_attn.weight', 'h.0.ln_cross_attn.bias', 'h.0.ln_cross_attn.weight', 'h.1.crossattention.c_attn.bias', 'h.1.crossattention.c_attn.weight', 'h.1.crossattention.c_proj.bias', 'h.1.crossattention.c_proj.weight', 'h.1.crossattention.q_attn.bias', 'h.1.crossattention.q_attn.weight', 'h.1.ln_cross_attn.bias', 'h.1.ln_cross_attn.weight', 'h.10.crossattention.c_attn.bias', 'h.10.crossattention.c_attn.weight', 'h.10.crossattention.c_proj.bias', 'h.10.crossattention.c_proj.weight', 'h.10.crossattention.q_attn.bias', 'h.10.crossattention.q_attn.weight', 'h.10.ln_cross_attn.bias', 'h.10.ln_cross_attn.weight', 'h.11.crossattention.c_attn.bias', 'h.11.crossattention.c_attn.weight', 'h.11.crossattention.c_proj.bias', 'h.11.crossattention.c_proj.weight', 'h.11.crossattention.q_attn.bias', 'h.11.crossattention.q_attn.weight', 'h.11.ln_cross_attn.bias', 'h.11.ln_cross_attn.weight', 'h.2.crossattention.c_attn.bias', 'h.2.crossattention.c_attn.weight', 'h.2.crossattention.c_proj.bias', 'h.2.crossattention.c_proj.weight', 'h.2.crossattention.q_attn.bias', 'h.2.crossattention.q_attn.weight', 'h.2.ln_cross_attn.bias', 'h.2.ln_cross_attn.weight', 'h.3.crossattention.c_attn.bias', 'h.3.crossattention.c_attn.weight', 'h.3.crossattention.c_proj.bias', 'h.3.crossattention.c_proj.weight', 'h.3.crossattention.q_attn.bias', 'h.3.crossattention.q_attn.weight', 'h.3.ln_cross_attn.bias', 'h.3.ln_cross_attn.weight', 'h.4.crossattention.c_attn.bias', 'h.4.crossattention.c_attn.weight', 'h.4.crossattention.c_proj.bias', 'h.4.crossattention.c_proj.weight', 'h.4.crossattention.q_attn.bias', 'h.4.crossattention.q_attn.weight', 'h.4.ln_cross_attn.bias', 'h.4.ln_cross_attn.weight', 'h.5.crossattention.c_attn.bias', 'h.5.crossattention.c_attn.weight', 'h.5.crossattention.c_proj.bias', 'h.5.crossattention.c_proj.weight', 'h.5.crossattention.q_attn.bias', 'h.5.crossattention.q_attn.weight', 'h.5.ln_cross_attn.bias', 'h.5.ln_cross_attn.weight', 'h.6.crossattention.c_attn.bias', 'h.6.crossattention.c_attn.weight', 'h.6.crossattention.c_proj.bias', 'h.6.crossattention.c_proj.weight', 'h.6.crossattention.q_attn.bias', 'h.6.crossattention.q_attn.weight', 'h.6.ln_cross_attn.bias', 'h.6.ln_cross_attn.weight', 'h.7.crossattention.c_attn.bias', 'h.7.crossattention.c_attn.weight', 'h.7.crossattention.c_proj.bias', 'h.7.crossattention.c_proj.weight', 'h.7.crossattention.q_attn.bias', 'h.7.crossattention.q_attn.weight', 'h.7.ln_cross_attn.bias', 'h.7.ln_cross_attn.weight', 'h.8.crossattention.c_attn.bias', 'h.8.crossattention.c_attn.weight', 'h.8.crossattention.c_proj.bias', 'h.8.crossattention.c_proj.weight', 'h.8.crossattention.q_attn.bias', 'h.8.crossattention.q_attn.weight', 'h.8.ln_cross_attn.bias', 'h.8.ln_cross_attn.weight', 'h.9.crossattention.c_attn.bias', 'h.9.crossattention.c_attn.weight', 'h.9.crossattention.c_proj.bias', 'h.9.crossattention.c_proj.weight', 'h.9.crossattention.q_attn.bias', 'h.9.crossattention.q_attn.weight', 'h.9.ln_cross_attn.bias', 'h.9.ln_cross_attn.weight']\n","You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.\n","load dataset:35877 split into train_dataset35841 and eval_dataset:36\n","/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:558: UserWarning: This DataLoader will create 16 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.\n","  warnings.warn(_create_warning_msg(\n","Traceback (most recent call last):\n","  File \"/content/Cantolater/main.py\", line 506, in <module>\n","    main(args)\n","  File \"/content/Cantolater/main.py\", line 266, in main\n","    train(\n","  File \"/content/Cantolater/main.py\", line 304, in train\n","    outputs = model(\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1511, in _wrapped_call_impl\n","    return self._call_impl(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1520, in _call_impl\n","    return forward_call(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/transformers/models/encoder_decoder/modeling_encoder_decoder.py\", line 590, in forward\n","    encoder_outputs = self.encoder(\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1511, in _wrapped_call_impl\n","    return self._call_impl(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1520, in _call_impl\n","    return forward_call(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/transformers/models/bert_generation/modeling_bert_generation.py\", line 802, in forward\n","    embedding_output = self.embeddings(\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1511, in _wrapped_call_impl\n","    return self._call_impl(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1520, in _call_impl\n","    return forward_call(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/transformers/models/bert_generation/modeling_bert_generation.py\", line 570, in forward\n","    inputs_embeds = self.word_embeddings(input_ids)\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1511, in _wrapped_call_impl\n","    return self._call_impl(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1520, in _call_impl\n","    return forward_call(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/sparse.py\", line 163, in forward\n","    return F.embedding(\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/nn/functional.py\", line 2237, in embedding\n","    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)\n","RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)\n"]}]},{"cell_type":"code","source":["!python /content/Cantolater/main.py --ispredict"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"liP-aRC76NH6","executionInfo":{"status":"ok","timestamp":1711895512077,"user_tz":-480,"elapsed":1658,"user":{"displayName":"gracias","userId":"12064270699339955558"}},"outputId":"df7d1a75-3af7-40c6-ba2e-5df15cfefd73"},"execution_count":9,"outputs":[{"output_type":"stream","name":"stdout","text":["2024-03-31 14:31:51.235135: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered\n","2024-03-31 14:31:51.235189: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered\n","2024-03-31 14:31:51.236510: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n","Traceback (most recent call last):\n","  File \"/content/Cantolater/main.py\", line 11, in <module>\n","    from transformers import (\n","  File \"<frozen importlib._bootstrap>\", line 1075, in _handle_fromlist\n","  File \"/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py\", line 1380, in __getattr__\n","    module = self._get_module(self._class_to_module[name])\n","  File \"/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py\", line 1390, in _get_module\n","    return importlib.import_module(\".\" + module_name, self.__name__)\n","  File \"/usr/lib/python3.10/importlib/__init__.py\", line 126, in import_module\n","    return _bootstrap._gcd_import(name[level:], package, level)\n","  File \"/usr/local/lib/python3.10/dist-packages/transformers/trainer.py\", line 59, in <module>\n","    from .data.data_collator import DataCollator, DataCollatorWithPadding, default_data_collator\n","  File \"/usr/local/lib/python3.10/dist-packages/transformers/data/__init__.py\", line 27, in <module>\n","    from .processors import (\n","  File \"/usr/local/lib/python3.10/dist-packages/transformers/data/processors/__init__.py\", line 15, in <module>\n","    from .glue import glue_convert_examples_to_features, glue_output_modes, glue_processors, glue_tasks_num_labels\n","  File \"/usr/local/lib/python3.10/dist-packages/transformers/data/processors/glue.py\", line 30, in <module>\n","    import tensorflow as tf\n","  File \"/usr/local/lib/python3.10/dist-packages/tensorflow/__init__.py\", line 48, in <module>\n","    from tensorflow._api.v2 import __internal__\n","  File \"/usr/local/lib/python3.10/dist-packages/tensorflow/_api/v2/__internal__/__init__.py\", line 11, in <module>\n","    from tensorflow._api.v2.__internal__ import distribute\n","  File \"/usr/local/lib/python3.10/dist-packages/tensorflow/_api/v2/__internal__/distribute/__init__.py\", line 8, in <module>\n","    from tensorflow._api.v2.__internal__.distribute import combinations\n","  File \"/usr/local/lib/python3.10/dist-packages/tensorflow/_api/v2/__internal__/distribute/combinations/__init__.py\", line 8, in <module>\n","    from tensorflow.python.distribute.combinations import env # line: 456\n","  File \"/usr/local/lib/python3.10/dist-packages/tensorflow/python/distribute/combinations.py\", line 33, in <module>\n","    from tensorflow.python.distribute import collective_all_reduce_strategy\n","  File \"/usr/local/lib/python3.10/dist-packages/tensorflow/python/distribute/collective_all_reduce_strategy.py\", line 32, in <module>\n","    from tensorflow.python.distribute import mirrored_strategy\n","  File \"/usr/local/lib/python3.10/dist-packages/tensorflow/python/distribute/mirrored_strategy.py\", line 34, in <module>\n","    from tensorflow.python.distribute.cluster_resolver import tfconfig_cluster_resolver\n","  File \"/usr/local/lib/python3.10/dist-packages/tensorflow/python/distribute/cluster_resolver/__init__.py\", line 27, in <module>\n","    from tensorflow.python.distribute.cluster_resolver.gce_cluster_resolver import GCEClusterResolver\n","  File \"/usr/local/lib/python3.10/dist-packages/tensorflow/python/distribute/cluster_resolver/gce_cluster_resolver.py\", line 24, in <module>\n","    from googleapiclient import discovery  # pylint: disable=g-import-not-at-top\n","  File \"/usr/local/lib/python3.10/dist-packages/googleapiclient/discovery.py\", line 45, in <module>\n","    from google.oauth2 import service_account\n","  File \"/usr/local/lib/python3.10/dist-packages/google/oauth2/service_account.py\", line 77, in <module>\n","    from google.auth import _service_account_info\n","  File \"/usr/local/lib/python3.10/dist-packages/google/auth/_service_account_info.py\", line 20, in <module>\n","    from google.auth import crypt\n","  File \"/usr/local/lib/python3.10/dist-packages/google/auth/crypt/__init__.py\", line 41, in <module>\n","    from google.auth.crypt import rsa\n","  File \"/usr/local/lib/python3.10/dist-packages/google/auth/crypt/rsa.py\", line 20, in <module>\n","    from google.auth.crypt import _cryptography_rsa\n","  File \"/usr/local/lib/python3.10/dist-packages/google/auth/crypt/_cryptography_rsa.py\", line 27, in <module>\n","    import cryptography.x509\n","  File \"/usr/local/lib/python3.10/dist-packages/cryptography/x509/__init__.py\", line 8, in <module>\n","    from cryptography.x509.base import (\n","  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\n","  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\n","  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\n","  File \"<frozen importlib._bootstrap_external>\", line 879, in exec_module\n","  File \"<frozen importlib._bootstrap_external>\", line 1012, in get_code\n","  File \"<frozen importlib._bootstrap_external>\", line 672, in _compile_bytecode\n","KeyboardInterrupt\n","^C\n"]}]}]}